//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlprotecdbEntities : DbContext
    {
        public AlprotecdbEntities()
            : base("name=AlprotecdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alojamiento> Alojamiento { get; set; }
        public virtual DbSet<Bobinado> Bobinado { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Eje> Eje { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Formulario> Formulario { get; set; }
        public virtual DbSet<InspeccionMedicion> InspeccionMedicion { get; set; }
        public virtual DbSet<Proceso> Proceso { get; set; }
        public virtual DbSet<PruebaElectricaFinal> PruebaElectricaFinal { get; set; }
        public virtual DbSet<PruebaElectricaInicial> PruebaElectricaInicial { get; set; }
        public virtual DbSet<Recepcion> Recepcion { get; set; }
        public virtual DbSet<Rodamiento> Rodamiento { get; set; }
        public virtual DbSet<TipoCatalogo> TipoCatalogo { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
