//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        public Catalogo()
        {
            this.Catalogo1 = new HashSet<Catalogo>();
            this.Cliente = new HashSet<Cliente>();
            this.Cliente1 = new HashSet<Cliente>();
            this.Cliente2 = new HashSet<Cliente>();
            this.Equipo = new HashSet<Equipo>();
        }
    
        public long idCatalogo { get; set; }
        public string valor { get; set; }
        public Nullable<long> idPadre { get; set; }
        public long idTipoCatalogo { get; set; }
        public bool estado { get; set; }
        public long creadoPor { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public long modificadoPor { get; set; }
    
        public virtual ICollection<Catalogo> Catalogo1 { get; set; }
        public virtual Catalogo Catalogo2 { get; set; }
        public virtual TipoCatalogo TipoCatalogo { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Cliente> Cliente1 { get; set; }
        public virtual ICollection<Cliente> Cliente2 { get; set; }
        public virtual ICollection<Equipo> Equipo { get; set; }
    }
}
