//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eje
    {
        public long idEje { get; set; }
        public Nullable<double> lecturaEntradaEjeFrontal { get; set; }
        public Nullable<double> lecturaEntradaEjePosterior { get; set; }
    }
}
