//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public long idEquipo { get; set; }
        public string codigoInterno { get; set; }
        public string claseMaquina { get; set; }
        public string numeroSerie { get; set; }
        public int rpm { get; set; }
        public Nullable<double> amp { get; set; }
        public string numeroInventarioCliente { get; set; }
        public double potenciaHP { get; set; }
        public Nullable<double> potenciakW { get; set; }
        public string claseAislamiento { get; set; }
        public string designacionNema { get; set; }
        public string frame { get; set; }
        public Nullable<int> voltaje { get; set; }
        public string factorServicio { get; set; }
        public long idCliente { get; set; }
        public long idModeloCatalogo { get; set; }
        public bool estado { get; set; }
        public long creadoPor { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public long modificadoPor { get; set; }
        public System.DateTime fechaModificacion { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
