//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcion
    {
        public long idRecepcion { get; set; }
        public int numero { get; set; }
        public bool reparadoAntes { get; set; }
        public int existeEstator { get; set; }
        public int estadoEstator { get; set; }
        public int existeRotor { get; set; }
        public int estadoRotor { get; set; }
        public int posicionCajaConexion { get; set; }
        public int existeCajaConexion { get; set; }
        public int estadoCajaConexion { get; set; }
        public int existeBaseCajaConexion { get; set; }
        public int estadoBaseCajaConexion { get; set; }
        public int existeVentilador { get; set; }
        public int estadoVentilador { get; set; }
        public int existeTapaVentilador { get; set; }
        public int estadoTapaVentilador { get; set; }
        public int existeTapaDelantera { get; set; }
        public int estadoTapaDelantera { get; set; }
        public int existePolea { get; set; }
        public int estadoPolea { get; set; }
        public int existeAcople { get; set; }
        public int estadoAcople { get; set; }
        public int existeBaseMotor { get; set; }
        public int estadoBaseMotor { get; set; }
        public string observacionesCliente { get; set; }
        public string diagnosticoFallas { get; set; }
        public string nombreEntrega { get; set; }
        public string cargoEntrega { get; set; }
        public string nombreRecibe { get; set; }
        public string cargoRecibe { get; set; }
        public string observaciones { get; set; }
        public string nombreInterventor { get; set; }
        public long idCliente { get; set; }
        public long idEquipo { get; set; }
        public long creadoPor { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public long modificadoPor { get; set; }
        public System.DateTime fechaModificacion { get; set; }
    }
}
