//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepcionEquipo
    {
        public long idRecepcionEquipo { get; set; }
        public int numero { get; set; }
        public bool reparadoAntes { get; set; }
        public bool existeEstator { get; set; }
        public int estadoEstator { get; set; }
        public bool existeRotor { get; set; }
        public int estadoRotor { get; set; }
        public int posicionCajaConexion { get; set; }
        public bool existeCajaConexion { get; set; }
        public int estadoCajaConexion { get; set; }
        public bool existeBaseCajaConexion { get; set; }
        public int estadoBaseCajaConexion { get; set; }
        public bool existeVentilador { get; set; }
        public int estadoVentilador { get; set; }
        public bool existeTapaVentilador { get; set; }
        public int estadoTapaVentilador { get; set; }
        public bool existeTapaFrontal { get; set; }
        public int estadoTapaFrontal { get; set; }
        public bool existeTapaPosterior { get; set; }
        public int estadoTapaPosterior { get; set; }
        public bool existePolea { get; set; }
        public int estadoPolea { get; set; }
        public bool existeAcople { get; set; }
        public int estadoAcople { get; set; }
        public bool existeBaseMotor { get; set; }
        public int estadoBaseMotor { get; set; }
        public bool existeCapacitorArranque { get; set; }
        public int estadoCapacitorArranque { get; set; }
        public bool existeCapacitorPermanente { get; set; }
        public int estadoCapacitorPermanente { get; set; }
        public bool existeCentrifugo { get; set; }
        public int estadoCentrifugo { get; set; }
        public bool existePlatinera { get; set; }
        public int estadoPlatinera { get; set; }
        public string observacionesCliente { get; set; }
        public string diagnosticoFallas { get; set; }
        public long idCliente { get; set; }
        public long idEquipo { get; set; }
        public long creadoPor { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public long modificadoPor { get; set; }
        public System.DateTime fechaModificacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
