//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rodamiento
    {
        public long idRodamiento { get; set; }
        public string referenciaFrontal { get; set; }
        public string referenciaPosterior { get; set; }
        public string fabricanteFrontal { get; set; }
        public string fabricantePosterior { get; set; }
    }
}
